import DefaultQuery from './queryType';
import TagType from './tagType';
import TaxonomyType from './taxonomyType';
import PostType from './postType';
import MediaType from './mediaType';
import DefaultMutation from './mutationType';
export * from './tagType';
export * from './imgType';
export * from './queryType';
export * from './settingsType';
export * from './userType';
export * from './catType';
export * from './languageType';
export * from './catType';
export { DefaultQuery, DefaultMutation };
export { TagType, TaxonomyType, PostType, MediaType };
